#!/bin/sh

set  -e

#DEBHELPER#

case "$1" in
	configure)
		aptKeyBinary=$(which apt-key)
		if ! [ -z "${aptKeyBinary}" ] && [ -x ${aptKeyBinary} ] ; then
			${aptKeyBinary} add /usr/share/keyrings/benoitguerin-keyring.gpg
		fi
		;;
esac

exit 0
